eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
#  config:
#    import: optional:configserver:http://localhost:8888
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          uri: http://localhost:7000
          predicates:
            - Path=/api/v1/students/**
        - id: schools
          uri: http://localhost:6000
          predicates:
            - Path=/api/v1/schools/**